### ISSUE TITLE
load data sections: data section .rodata.cst32: can't get BTF: type .rodata.cst32: not found"

### ISSUE THREAD

**Issue by vincentmli** [cilium/ebpf#553] opened 2022-01-31 17:43 UTC
**Describe the bug**
It appears elf_reader does not parse .rodata.cst32 section with constant defined below in cilium `bpf/node_config.h` that is included in `bpf/bpf_lxc.c`, also see https://github.com/cilium/cilium/issues/18616 for more background info

grep 'VTEP' /var/run/cilium/state/globals/node_config.h 

```
#define ENABLE_VTEP 1
#define VTEP_ENDPOINT (__u32[]){ 0xeb48a90a, 0xec48a90a, 0xed48a90a, 0xee48a90a, }
#define VTEP_MAC (__u64[]){ 0x562e984c3682, 0x552e984c3682, 0x542e984c3682, 0x532e984c3682, }
#define VTEP_NUMS 4
```
`.rodata.cst32` will be generated by compiler for VTEP_MAC member in `bpf_lxc.o` and this seems normal from compiler side https://lore.kernel.org/bpf/41e809b6-62ac-355a-082f-559fa4b1ffea@fb.com/

```
readelf -x .rodata.cst32 /var/run/cilium/state/1378_next_fail/bpf_lxc.o

Hex dump of section '.rodata.cst32':
  0x00000000 82364c98 2e560000 82364c98 2e550000 .6L..V...6L..U..
  0x00000010 82364c98 2e540000 82364c98 2e530000 .6L..T...6L..S..
```

so cilium/ebpf needs to support rodata.cst32 

I have limited knowledge on cilium/ebpf and BTF in general

attempted below but no success.

```
--- a/vendor/github.com/cilium/ebpf/elf_reader.go
+++ b/vendor/github.com/cilium/ebpf/elf_reader.go
@@ -75,7 +75,7 @@ func LoadCollectionSpecFromReader(rd io.ReaderAt) (*CollectionSpec, error) {
                        sections[idx] = newElfSection(sec, mapSection)
                case sec.Name == ".maps":
                        sections[idx] = newElfSection(sec, btfMapSection)
-               case sec.Name == ".bss" || sec.Name == ".data" || strings.HasPrefix(sec.Name, ".rodata"):
+               case sec.Name == ".bss" || sec.Name == ".data" || strings.HasPrefix(sec.Name, ".rodata") || strings.HasPrefix(sec.Name, ".rodata.cst32"):
```

**To Reproduce**
Steps to reproduce the behavior. Please include:

Yonghong from BPF mailinglist gives a sample code, I guess that can be a simple reproducer 

```
$ cat t.c
struct t {
   long c[2];
   int d[4];
};
struct t g;
int test()
{
    struct t tmp  = {.c = {1, 2}, .d = {3, 4}};
    g = tmp;
    return 0;
}

$ clang -target bpf -O2 -c t.c
$ llvm-readelf -S t.o
...
   [ 4] .rodata.cst32     PROGBITS        0000000000000000 0000a8 000020 
20  AM  0   0  8
```

**Expected behavior**
expect cilium/ebpf elf_reader support .rodata.cst32

**Comment by vincentmli** [comment] 2022-01-31 20:17
> 



> **Describe the bug** It appears elf_reader does not parse .rodata.cst32 section with constant defined below in cilium `bpf/node_config.h` that is included in `bpf/bpf_lxc.c`, also see [cilium/cilium#18616](https://github.com/cilium/cilium/issues/18616) for more background info
> 
> grep 'VTEP' /var/run/cilium/state/globals/node_config.h
> 
> ```
> #define ENABLE_VTEP 1
> #define VTEP_ENDPOINT (__u32[]){ 0xeb48a90a, 0xec48a90a, 0xed48a90a, 0xee48a90a, }
> #define VTEP_MAC (__u64[]){ 0x562e984c3682, 0x552e984c3682, 0x542e984c3682, 0x532e984c3682, }
> #define VTEP_NUMS 4
> ```
> 
> `.rodata.cst32` will be generated by compiler for VTEP_MAC member in `bpf_lxc.o` and this seems normal from compiler side https://lore.kernel.org/bpf/41e809b6-62ac-355a-082f-559fa4b1ffea@fb.com/
> 
> ```
> readelf -x .rodata.cst32 /var/run/cilium/state/1378_next_fail/bpf_lxc.o
> 
> Hex dump of section '.rodata.cst32':
>   0x00000000 82364c98 2e560000 82364c98 2e550000 .6L..V...6L..U..
>   0x00000010 82364c98 2e540000 82364c98 2e530000 .6L..T...6L..S..
> ```
> 
> so cilium/ebpf needs to support rodata.cst32
> 
> I have limited knowledge on cilium/ebpf and BTF in general

> ```
> --- a/vendor/github.com/cilium/ebpf/elf_reader.go
> +++ b/vendor/github.com/cilium/ebpf/elf_reader.go
> @@ -75,7 +75,7 @@ func LoadCollectionSpecFromReader(rd io.ReaderAt) (*CollectionSpec, error) {
>                         sections[idx] = newElfSection(sec, mapSection)
>                 case sec.Name == ".maps":
>                         sections[idx] = newElfSection(sec, btfMapSection)
> -               case sec.Name == ".bss" || sec.Name == ".data" || strings.HasPrefix(sec.Name, ".rodata"):
> +               case sec.Name == ".bss" || sec.Name == ".data" || strings.HasPrefix(sec.Name, ".rodata") || strings.HasPrefix(sec.Name, ".rodata.cst32"):
> ```

I did above because I was thinking about following message from slack from @lmb 

"
re what has to change in the library: https://github.com/cilium/ebpf/blob/d1a8e061b8f22fb07e040d5dcce420637211ca51/elf_reader.go#L78-L79 isn't smart enough to pick up .rodata.cst32
"
but based on code below, `ec.sections` does pick up the `.rodata.cst32` and stored in `ec.sections` unless I misunderstand above quoted comment

```
func (ec *elfCode) loadDataSections(maps map[string]*MapSpec) error {
        for _, sec := range ec.sections {
                if sec.kind != dataSection {
                        continue
                }

                if sec.references == 0 {
                        // Prune data sections which are not referenced by any
                        // instructions.
                        continue
                }

                if ec.btf == nil {
                        return errors.New("data sections require BTF, make sure all consts are marked as static")
                }

                var datasec *btf.Datasec
                if err := ec.btf.FindType(sec.Name, &datasec); err != nil {
                        return fmt.Errorf("data section %s: can't get BTF: %w", sec.Name, err)
                }

```

I think it is the `btf.Spec` missing `.rodata.cst32` as shown from below

```
func (s *Spec) FindType(name string, typ interface{}) error {
        typValue := reflect.ValueOf(typ)
        if typValue.Kind() != reflect.Ptr {
                return fmt.Errorf("%T is not a pointer", typ)
        }

        typPtr := typValue.Elem()
        if !typPtr.CanSet() {
                return fmt.Errorf("%T cannot be set", typ)
        }

        wanted := typPtr.Type()
        if !wanted.AssignableTo(reflect.TypeOf((*Type)(nil)).Elem()) {
                return fmt.Errorf("%T does not satisfy Type interface", typ)
        }

        var candidate Type
        for _, typ := range s.namedTypes[essentialName(name)] { <===here search rodata.cst32 in btf.Spec.NamedTypes
                if reflect.TypeOf(typ) != wanted {
                        continue
                }

                // Match against the full name, not just the essential one.
                if typ.TypeName() != name {
                        continue
                }

                if candidate != nil {
                        return fmt.Errorf("type %s: multiple candidates for %T", name, typ)
                }

                candidate = typ
        }

        if candidate == nil {
                return fmt.Errorf("type %s: %w", name, ErrNotFound) <======error not found
        }

        typPtr.Set(reflect.ValueOf(candidate))

        return nil

```

`btf.Spec.NamedTypes` is populated here

```
// inflateRawTypes takes a list of raw btf types linked via type IDs, and turns
// it into a graph of Types connected via pointers.
//
// Returns a map of named types (so, where NameOff is non-zero) and a slice of types
// indexed by TypeID. Since BTF ignores compilation units, multiple types may share
// the same name. A Type may form a cyclic graph by pointing at itself.
func inflateRawTypes(rawTypes []rawType, rawStrings stringTable) (types []Type, namedTypes map[string][]NamedType, err error) {
..............CUT.....
        types = make([]Type, 0, len(rawTypes))
        types = append(types, (*Void)(nil))
        namedTypes = make(map[string][]NamedType)

        for i, raw := range rawTypes {
                var (
                        // Void is defined to always be type ID 0, and is thus
                        // omitted from BTF.
                        id  = TypeID(i + 1)
                        typ Type
                )

                name, err := rawStrings.Lookup(raw.NameOff)
                if err != nil {
                        return nil, nil, fmt.Errorf("get name for type id %d: %w", id, err)
                }

                switch raw.Kind() {
....................CUT......
                case kindDatasec:
                        btfVars := raw.data.([]btfVarSecinfo)
                        vars := make([]VarSecinfo, 0, len(btfVars))
                        for _, btfVar := range btfVars {
                                vars = append(vars, VarSecinfo{
                                        Offset: btfVar.Offset,
                                        Size:   btfVar.Size,
                                })
                        }
                        for i := range vars {
                                fixup(btfVars[i].Type, kindVar, &vars[i].Type)
                        }
                        typ = &Datasec{id, name, raw.SizeType, vars}

                types = append(types, typ)

                if named, ok := typ.(NamedType); ok {
                        if name := essentialName(named.TypeName()); name != "" {
                                namedTypes[name] = append(namedTypes[name], named). <=======here
                        }
                }
        }

```

and `inflateRawTypes` is eventually called from below

```
func loadKernelSpec() (*Spec, error) {
        release, err := unix.KernelRelease()
        if err != nil {
                return nil, fmt.Errorf("can't read kernel release number: %w", err)
        }

        fh, err := os.Open("/sys/kernel/btf/vmlinux"). <=====open vmlinux
        if err == nil {
                defer fh.Close()

                return LoadRawSpec(fh, internal.NativeEndian) <===call inflateRawTypes
        }

```

Please let me know I am missing anything here :-)

**Comment by ti-mo** [comment] 2022-02-01 09:45
@vincentmli Thanks for the detailed report, I'm taking a look. It seems `.rodata.cst32` simply does not have accompanying BTF info.

**Comment by vincentmli** [comment] 2022-02-01 17:46
Thanks @ti-mo for looking into it, yes you are right. btf.Spec is populated by vmlinux, but elf object file from user may have compiler generated section not having accompanying BTF type from vmlinux, this could cause inconsistency

**Comment by ti-mo** [comment] 2022-02-03 10:35
@vincentmli could you get me a copy of that `bpf_lxc.o`? Apparently this particular `.rodata.cst32` section _does_ have references, so we can't simply skip loading it as Yonghong/Andrii are suggesting on the list. (we already skip `.rodata*` maps without references)

Making BTF optional for global data maps is straightforward, but I'd like the ELF to make sure I craft the right test for it.

Also, you might need to find a way to make those VTEP endpoints not end up in .rodata, because iproute2 uses a libbpf version that doesn't support .rodata yet -- at least that's what it complained about when I used it to load Yonghong's reproducer. Cilium still uses iproute2 to load its datapath, it's just that map migrations are the first part we converted to use `cilium/ebpf` and it's the first part in the chain. You'll find more trouble once this issue has been fixed.. :)

**Comment by vincentmli** [comment] 2022-02-03 15:33
@ti-mo I attached the object file with .txt suffix so I can upload here, thanks again for looking into this issue.
[bpf_lxc.o.txt](https://github.com/cilium/ebpf/files/7995898/bpf_lxc.o.txt)

**Comment by ti-mo** [comment] 2022-02-04 11:20
@vincentmli I've done some more digging and replied on the list. Could you try removing the enclosing `{}` scope within the ifdef you added in the VTEP patch? This might have an effect on the stack layout. We could teach the library to accept the type of relocation emitted by this piece of C code, but I'd like to wait and see what the compiler folks have to say before we commit to a workaround & adding tests.

**Comment by vincentmli** [comment] 2022-02-04 19:06
> Also, you might need to find a way to make those VTEP endpoints not end up in .rodata, because iproute2 uses a libbpf version that doesn't support .rodata yet -- at least that's what it complained about when I used it to load Yonghong's reproducer. Cilium still uses iproute2 to load its datapath, it's just that map migrations are the first part we converted to use `cilium/ebpf` and it's the first part in the chain. You'll find more trouble once this issue has been fixed.. :)

I can limit the number of VTEPs to 2 instead of 4, in that case, no any .rodata created

**Comment by vincentmli** [comment] 2022-02-04 19:13
> @vincentmli I've done some more digging and replied on the list. Could you try removing the enclosing `{}` scope within the ifdef you added in the VTEP patch? This might have an effect on the stack layout. We could teach the library to accept the type of relocation emitted by this piece of C code, but I'd like to wait and see what the compiler folks have to say before we commit to a workaround & adding tests.

@ti-mo I replied on the list and I did what you suggested to remove the enclosing `{}`, seems no effect, here attach the new object file, yonghong is asking for a reproducer .c file, I could not come up with a simple reproducer .c file due to my limited knowledge on this, here is my attempt for reproducer but no .rodata genereated

```
typedef unsigned int __u32;
typedef unsigned long long __u64;

#define VTEP_ENDPOINT (__u32[]){0xeb48a90a, 0xec48a90a, 0xed48a90a, 0xee48a90a, }
/* HEX representation of VTEP IP
 * 10.169.72.235, 10.169.72.236, 10.169.72.237, 10.169.72.238
 */
#define VTEP_MAC (__u64[]){0x562e984c3682, 0x552e984c3682, 0x542e984c3682, 0x532e984c3682}
/* VTEP MAC address
 * 82:36:4c:89:2e:56, 82:36:4c:89:2e:55, 82:36:4c:89:2e:54, 82:36:4c:89:2e:53
 */
#define VTEP_NUMS 4

int handle_ipv4_from_lxc()
{
        __u32 tunnel_endpoint = 0;
        __u64 vtep_mac = 0;
        int i;

      for (i = 0; i < VTEP_NUMS; i++) {
           if (tunnel_endpoint == VTEP_ENDPOINT[i]) {
                      vtep_mac = VTEP_MAC[i];
                      break;
           }
      }
      return i;

}
```
[bpf_lxc.o.txt](https://github.com/cilium/ebpf/files/8005568/bpf_lxc.o.txt)

**Comment by lmb** [comment] 2022-04-21 17:15
Did you get anywhere with this @ti-mo? Seems like a compiler bug?

**Comment by ti-mo** [comment] 2022-04-26 13:01
Haven't had the time to dig into this more. From my perspective, it looks like a compiler bug, but I've been unable to come up with a solid repro I can take to the list.

We can close this for now, this might not end up needing fixing in the lib.

**Closed by ti-mo** 2022-04-26 13:01 UTC
Labels: bug
