### ISSUE TITLE
return EPERM when creating ebpf map

### ISSUE THREAD

**Issue by weli-l** [cilium/ebpf#1617] opened 2024-11-29 03:19 UTC
### Describe the bug

1. deploy cilium in my cluster
2. deploy my daemonset( No CAP_SYS_ADMIN capability), in this daemonset I need to creat ebpf map
3. in step 2 ,return err.
4. If I add CAP_SYS_ADMIN and deploy in root mode for my daemonset ,everything goes well
Why I need to add  CAP_SYS_ADMIN and deploy in root mode for daemonset, because If only daemonset exists in the cluster, there is not need  add CAP_SYS_ADMIN  to create an ebpf map.

### How to reproduce

1. deploy cilium in my cluster
2. deploy my daemonset( No CAP_SYS_ADMIN capability), in this daemonset I need to creat ebpf map
3. in step 2 ,return err.
4. If I add CAP_SYS_ADMIN and deploy in root mode for my daemonset ,everything goes well
Why I need to add  CAP_SYS_ADMIN and deploy in root mode for daemonset, because If only daemonset exists in the cluster, there is not need  add CAP_SYS_ADMIN  to create an ebpf map.

### Version information

github.com/cilium/ebpf v0.9.3

**Comment by florianl** [comment] 2024-11-29 09:53
eBPF in general (including the creation of eBPF maps) requires extended privileges. These required extended privileges are independent of the deployment method. You can find more documentation about these capabilities and how they change in Linux over different versions at https://docs.ebpf.io/linux/#capabilities.

For more details on privilges with cilium, pelase check out https://docs.cilium.io/en/latest/security/restrict-pod-access/#restricting-privileged-cilium-pod-access.  

Closing this issue, as it is not a bug.

**Closed by florianl** 2024-11-29 09:53 UTC
Labels: bug
