### ISSUE TITLE
field “xxx” is a bitfield: not supported

### ISSUE THREAD

**Issue by wrsrap** [cilium/ebpf#604] opened 2022-03-22 06:42 UTC
I hook the “net_dev_xmit“ tracepoint，try to parse the packet with struct iphdr：
loading objects: field NetDevStartXmitHook: program net_dev_start_xmit_hook: CO-RE relocations: relocate struct#63["iphdr"]: target struct#38880["iphdr"]: target struct#38880["iphdr"]: field "ihl" is a bitfield: not supported

go1.16.5
Linux localhost.localdomain 4.18.0-305.25.1.el8_4.x86_64

**Comment by florianl** [comment] 2022-03-22 08:38
There is work going on to support bitfields with PR https://github.com/cilium/ebpf/pull/573/.
This report seems also to be a duplicate of issue https://github.com/cilium/ebpf/issues/384.

**Comment by lmb** [comment] 2022-03-22 11:17
Florian has pointed you in the right direction, feel free to test the PR. Please search the issue tracker before creating new issues.

**Closed by lmb** 2022-03-22 11:17 UTC
Labels: bug

**Comment by lilong89** [comment] 2022-03-25 14:12
> There is work going on to support bitfields with PR #573. This report seems also to be a duplicate of issue #384.

Thank u for your patient

**Comment by lilong89** [comment] 2022-03-25 14:18
> Florian has pointed you in the right direction, feel free to test the PR. Please search the issue tracker before creating new issues.

 Thank u , i'll pay attention next time.

**Comment by ti-mo** [comment] 2022-03-29 14:18
https://github.com/cilium/ebpf/pull/573 was just merged, please give it a try.
