### ISSUE TITLE
has to have BTF in order to use bpf_spin_lock

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [cilium/ebpf#1524] opened 2024-07-23 11:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.14.13 and lower than v1.15.0

### What happened?

use bpf2go, met verifier error:  has to have BTF in order to use bpf_spin_lock

```
struct cluster_stats_key {
    __u64 netns_cookie;
    __u32 cluster_id;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(key_size, sizeof(struct cluster_stats_key));
    __uint(value_size, sizeof(struct cluster_stats));
    __uint(map_flags, BPF_F_NO_PREALLOC);
    __uint(max_entries, MAP_SIZE_OF_CLUSTER);
} map_of_cluster_stats SEC(".maps");

struct cluster_sock_data {
    __u32 cluster_id;
};

struct {
    __uint(type, BPF_MAP_TYPE_SK_STORAGE);
    __uint(map_flags, BPF_F_NO_PREALLOC);
    __type(key, int);
    __type(value, struct cluster_sock_data);
} map_of_cluster_sock SEC(".maps");

  bpf_spin_lock(&stats->lock);
  stats->active_connections += delta;
  bpf_spin_unlock((&stats->lock);

```

### How can we reproduce the issue?

run the code above

### Cilium Version

v0.15.0

### Kernel Version

6.19

### Kubernetes Version

1.23.17

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment] 2024-07-24 04:16
The code snippet seems to be incomplete, which is likely to hinder any response. Specifically, it doesn't look fully formed and I see references to a `stats` variable that isn't declared in the code snippet.

I've moved this tentatively over to cilium/ebpf, although it's not clear to me whether this is related to the library at all.

**Comment by ti-mo** [comment] 2024-09-05 13:47
It's not clear to me what the problem is, since both the code and any error messages are incomplete. Closing this since it's unlikely to be a bug or issue with the lib. If you have questions around how to use spinlocks with the lib, please search our GH discussions (https://github.com/cilium/ebpf/discussions) or create a new one.

**Closed by ti-mo** 2024-09-05 13:47 UTC
