### ISSUE TITLE
can't generate types

### ISSUE THREAD

**Issue by Benjamin-Yim** [cilium/ebpf#626] opened 2022-04-17 16:02 UTC
**Describe the bug**
can't generate types.

**To Reproduce**
1. get file  https://github.com/iovisor/bcc/blob/master/libbpf-tools/opensnoop.bpf.c
2. generate 

```sh
make -C ..
Error: can't write /ebpf/examples/opensnoop/bpf_bpfel.go: can't generate types: template: common:19:4: executing "common" at <$.TypeDeclaration>: error calling TypeDeclaration: struct#12["args_t"]: field 0: type pointer#13[target=#14]: not supported
```

**Expected behavior**

**Comment by lmb** [comment] 2022-04-17 23:19
The problem is https://github.com/iovisor/bcc/blob/7c02284faa2968d86720f416ea51cc74d446ab37/libbpf-tools/opensnoop.h#L10 which contains a pointer. There is no portable way to exchange pointers between Go and BPF, so they aren't implemented.

As a work around, try passing `-no-global-types` to bpf2go. This will suppress generating types for map values. You can then opt in to the types you want by passing `-type foo -type bar ...`.

**Comment by Benjamin-Yim** [comment] 2022-04-18 02:01
Thanks ，I try。
BUT ， i try [oomkill](https://github.com/iovisor/bcc/blob/master/libbpf-tools/oomkill.bpf.c)
error :
```
2022/04/18 09:58:12 loading objects: field KprobeOomKillProcess: program kprobe_oom_kill_process: load program: permission denied: R1 type=ctx expected=fp
; int kprobe_oom_kill_process(struct pt_regs *ctx, struct oom_control *oc, const char *message) {
0: (bf) r8 = r2
R2 !read_ok
processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
exit status 1
```

code :
```c
// +build ignore

#include "oomkill.h"

char __license[] SEC("license") = "Dual MIT/GPL";

struct {
	__uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
	__uint(key_size, sizeof(u32));
	__uint(value_size, sizeof(u32));
} events SEC(".maps");

SEC("kprobe/oom_kill_process")
int kprobe_oom_kill_process(struct pt_regs *ctx, struct oom_control *oc, const char *message) {
	struct data_t data;
	data.fpid  = bpf_get_current_pid_tgid() >> 32;
	data.tpid  = BPF_CORE_READ(oc, chosen, tgid);
	data.pages = BPF_CORE_READ(oc, totalpages);
	bpf_get_current_comm(&data.fcomm, sizeof(data.fcomm));
	bpf_probe_read_kernel(&data.tcomm, sizeof(data.tcomm), BPF_CORE_READ(oc, chosen, comm));
	bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &data, sizeof(data));
	return 0;
}
```

**Comment by ti-mo** [comment] 2022-04-20 11:51
@Benjamin-Yim The verifier error above is completely unrelated. The bpf program you pasted from bcc uses the `BPF_KPROBE` macro to declare the function signature, which you've removed in your example here.

I think @lmb answered your initial question, feel free to reply if that didn't solve the problem. Closing this for now.

**Closed by ti-mo** 2022-04-20 11:51 UTC
Labels: bug
