### ISSUE TITLE
After NewMapWithOptions on userspace, how to get the map and use it in bpf program ?

### ISSUE THREAD

**Issue by glenn-wang** [cilium/ebpf#452] opened 2021-10-19 16:58 UTC
For example:
`bpf_map_lookup_elem(&map, &key) ` in bpf program how to get the `map` created on userspace through calling `NewMapWithOptions ()`

Or in another way, how to use libbpf function `bpf_map__set_max_entries()` in  cilium/ebpf to set the max_entries of bpf map on userspace ?

My target is to set the max_entries of bpf map on userspace and use the map in bpf program.

**Comment by lmb** [comment] 2021-10-20 12:18
Closing since this is not a bug or feature request. The slack channel is the right place for this.

**Closed by lmb** 2021-10-20 12:18 UTC

**Comment by glenn-wang** [comment] 2021-10-20 13:21
@lmb

Whether cilium/ebpf  now support  creating map with `NewMapWithOptions`  on userpsace, and use the map in bpf  program ?
